Adjust the dimensions of `top-bar` and `annotator-toolbar` on mobile
hypothesis/client pull request #2745
Opened 2020-11-19 11:11 UTC by esanzgar

On mobile screen sizes, buttons get a minimum recommended size (following Apple's Human Interface Guidelines). To accommodate for that, `top-bar` height and `annotator-toobar` width must be adjusted accordingly.

Final result:
![image](https://user-images.githubusercontent.com/8555781/99658760-39360280-2a60-11eb-914a-bd4f3f3b25ee.png)

2020-11-19 11:19 UTC, esanzgar commented
I did not tested it on real mobile device, but on device emulator.

2020-11-19 13:55 UTC, lyzadanger requested changes
Hi! This is moving in a good direction, thank you!

Here is a screenshot from my iPhone (8):

![image](https://user-images.githubusercontent.com/439947/99674867-96bc5600-2a44-11eb-821d-df999b906f25.png)

Note that the left side and border of the buttons are cut off. This is going to be tricky to account for, as we simply don't quite have enough room for the 44px-wide button targets to the left of the sidebar content. But perhaps you can brainstorm something? It might require positioning the two lower buttons and nudging them to the right by a few pixels. It might need more cleverness than that. I'm not sure!

2020-11-20 10:05 UTC, esanzgar commented
@lyzadanger, unfortunately moving the two lower buttons to the right by a few pixel makes it to overlap with other content:

![image](https://user-images.githubusercontent.com/8555781/99787627-49adb200-2b20-11eb-9c97-94877a1ca837.png)

2020-11-20 12:54 UTC, esanzgar commented
I decided to make the sidebar a little bit smaller:
![image](https://user-images.githubusercontent.com/8555781/99802347-dadc5300-2b37-11eb-9458-c8951b8840db.png)

2020-11-20 14:02 UTC, lyzadanger requested changes
Hi @esanzgar 

Unfortunately, you've inherited a larger design issue here related to proportional dimensions of the sidebar on narrow-width device viewports. A larger restructure is needed her in future to have a more truly adaptive layout for various viewports/constraints.

For the purposes of making the buttons look and feel right on viewports that are in the iPhone-ish smartphone range, I think we may need an interim compromise.

What I'd suggest is hand-sizing these buttons/targets on narrow viewports to be oh, say, 38px wide or perhaps 40px—whatever the maximum width that we can fit on-screen for viewports in the target problem area (iPhone 8-ish). I totally acknowledge that this sucks—it's smaller than HIG suggest, but still larger than the button targets would be with no intervention.

I believe what we need to do in the future is refactor these narrow-viewport sidebar affordances—we can't be successful trying to position/fit/size buttons that have absolute dimensions but also have a dependency on a relative-unit-sized layout.

I'd like a sanity check from @robertknight on my general perspective here.

2020-11-20 16:43 UTC, esanzgar commented on src/styles/annotator/annotator.scss
> +    width: 84%;
I have checked on the range of screen width (<= 380px and >=240px) that displayed this issue and this solution seems to resolve the cutting-off of the buttons, while still adhering to Apple's HIG.

2020-11-20 16:49 UTC, lyzadanger commented on src/styles/annotator/annotator.scss
> +    width: 84%;
Sorry, I should have also mentioned the other pushback we're likely to encounter: we need to take significant pains not to reduce the width of the sidebar, as that is the content that the user needs to interact with. That real estate is very precious.

2020-11-20 16:51 UTC, esanzgar commented on src/styles/annotator/annotator.scss
> +    width: 84%;
@lyzadanger, please let me know if you want me to implement your proposed solution (resizing the buttons on narrow-width screens) instead.

Previous conversation: https://hypothes-is.slack.com/archives/C1M8NH76X/p1605782090037200

2020-11-20 16:52 UTC, lyzadanger commented on src/styles/annotator/annotator.scss
> +    width: 84%;
Yes, please. We need to fix the bigger picture here—what I'm proposing is interim—but we don't have the time to bite this off just now.

2020-11-23 16:43 UTC, esanzgar commented
I implemented @lyzadanger's interim solution: reducing the size of the buttons in the `annotator-bar` for all mobile devices (even on large screen devices) without affecting the size of the sidebar.

The final size of the buttons are 22px. This is a comprise to get the bigger possible `annotator-bar` buttons without cropping them. This is a screenshoot on an 320px wide screen (iPhone):

![image](https://user-images.githubusercontent.com/8555781/99989324-c48dfb80-2db2-11eb-9f48-b98381f37bb1.png)

On screens smaller than 320px wide the `annotator-bar` buttons get cropped a little. There are very few devices with screen narrower than 320px.

2020-11-23 17:27 UTC, lyzadanger approved these changes
Thanks for working through this and implementing an interim compromise.

2020-11-24 08:29 UTC, merged