Display the annotation header on the top-level annotation
hypothesis/client pull request #3420
Opened 2021-05-17 11:45 UTC by esanzgar

This PR enforces the annotation header to be always present, even if the
top level annotation is hidden by a filter. The annotation header
contains the document target. This information is specially important
in the context of the notebook, where annotations from different
documents are displayed together.

Initially, I included the `AnnotationHeader` component directly into the
`Thread` component, assuming the `isEditing` prop to be always `false`.
However, on two cases the annotation header is displayed differently if
the annotation is actively being edited. Hence, I decided  the best
approach was to instruct `Annotation` component to only display the header
by adding an extra prop `visibility` which can take three values:
`hidden`, `visible` or `header-only`.

On the notebook context:

Before  | After
------- | -------
![image](https://user-images.githubusercontent.com/8555781/118481786-256c1000-b714-11eb-9587-c92eec4a5146.png) | ![image](https://user-images.githubusercontent.com/8555781/118481312-a1b22380-b713-11eb-84ae-0bc197bce1ea.png)

On the sidebar context:

Before  | After
------- | -------
![image](https://user-images.githubusercontent.com/8555781/118482013-75e36d80-b714-11eb-91cd-6f829e88e48a.png) | ![image](https://user-images.githubusercontent.com/8555781/118481623-f81f6200-b713-11eb-84c8-9818a3bc8d9f.png)

Closes # 3250

2021-05-18 13:35 UTC, lyzadanger requested changes
Given the current state of things, constraints and needs, I think that this is a reasonable approach for now. 

I’d like to see if we can find another way to address layout for the root-annotation-header-only state so that we don’t end up with duplicative logic in the `Thread` component and/or a fragile layout. As I mention later here, I’d like to understand what the layout challenge you were solving was…

This work highlights a couple of pre-existing weaknesses:

* Inconsistency in vertical layout in rhythm and general design tuning that could be improved in threaded layouts.
* A certain amount of logical “confusion” about what metadata belongs to a thread vs. what is part of an annotation.

With respect to the former, I think our continuing work on design consistency and shared patterns should help in the long term.

With respect to the latter, the introduced `visibility` logic in `AnnotationHeader` feels a bit awkward, but I think it’s acceptable for now so that we can address this task without refactoring the entirety of 	`Annotation` and/or `Thread`. I’d argue that document information is probably more associated with a thread than a single annotation, so we can perhaps revisit this later? This may go along with work to improve the header in general—for example, it’s been requested that we consider not showing the group name in thread-card headers in the sidebar context, as all threads/annotations are within the same (focused) group. But in the interest of supporting the completion of this task, I’ll put that aside for now!

I’d like to see if there is an alternative way we can address:

`// Do not fix vertical alignment for the first thread`

in `Thread`. It would be nice to do away with the `showAnnotationHeader` logic entirely, and let the logical checks within the `annotationContent` memoized function take care of everything. It also seems like the logic may be duplicated between `showAnnotationHeader` and `annotationContent`?

Can you help me understand a little better what the styling/layout needs are here and what you ran into? I’m wondering if there’s another way to fix this without needing the logic in this component.

2021-05-18 13:35 UTC, lyzadanger commented on src/sidebar/components/Thread.js
> +          <div
Let's see if we can find another way to address this styling issue!

2021-05-18 13:35 UTC, lyzadanger commented on src/sidebar/components/test/Thread-test.js
> +      assert.equal(wrapper.find('Annotation').prop('visibility'), 'hidden');
I think the test description needs to change, as an `Annotation` is rendered, technically.

2021-05-19 12:43 UTC, esanzgar commented
Close in favour of #3423, which is a little bit simpler solution.

2021-05-19 12:43 UTC, closed without merging