Add stricter types for the discovery `Message`
hypothesis/client pull request #3937
Opened 2021-11-17 14:13 UTC by esanzgar

More stricter types allows to reduce errors during development and
better ergonomics as IDE are able to add accurate autocomplete. Before,
`PortProvider` allowed to listen for all short of frame combinations,
while `PortFinder#discover` allowed to all frames as argument. Now, the
set of these possibilities is reduced to only valid combinations.

In `PortFinder#discover`, the addition of types, makes the check of
valid combinations of frames unnecessary.

The price to pay for these stricter types is a bit more verbose types,
and in the case of `PortFinder#discover` the use of conditional types.

Example in `PortFinder`:

https://user-images.githubusercontent.com/8555781/142216237-16c5bf25-cb6e-4578-b4f9-4be6612740a0.mov

Example in `PortProvider`:

https://user-images.githubusercontent.com/8555781/142216284-e7366305-3268-4ef3-bce8-0576c47d825c.mov

2021-11-17 14:14 UTC, esanzgar commented on src/shared/port-finder.js
> +            /** @type {Message} */ ({
It is a pity that TS is not able to understand that the combination of `frame1` and `frame2` is a valid combination in `Message`.

2021-11-25 12:33 UTC, esanzgar commented on src/shared/port-finder.js
> -
This check is unnecessary because of the stricter types.

2021-11-30 10:21 UTC, robertknight requested changes
I don't think we should make the changes to the `Message` type proposed here. Unfortunately the error messages that TS currently produces when trying to construct a `Message` are pretty difficult to follow, even for me as someone who knows the language pretty well. We know that it is fine to use a cast, but this might not be obvious to someone else. In contrast the equivalent runtime code for checking compatibility of source and destination was easy to follow. I also think the previous `Message` type was easier for new developers to look at and understand.

The change to parametrize `PortFinder` is OK, though I noted that generic parameter names (`T`) should only be used when the meaning is obvious.

2021-12-09 10:58 UTC, esanzgar commented
This doesn't seem to bring very obvious benefits.

2021-12-09 10:58 UTC, closed without merging