Convert the content of the `name` attribute to lowercase: `<meta name="[content to lowercase ]">`
hypothesis/client pull request #4203
Opened 2022-02-10 15:53 UTC by esanzgar

Previously the following attributes in the meta tag:

```
<meta name="DC_IDENTIFIER" .../>
<meta name="EPRINTS.TITLE_" .../>
<meta property="OG:URL" .../>
<meta name="CITATION_DOI" .../>
<meta name="PRISM_TITLE" .../>
<meta name="TWITTER:SITE" .../>
```

produced a metadata dictionary like this:

```
{
  dc: {IDENTIFIER: [...] },
  eprints: {TITLE: [...]},
  facebook: {URL: [...]},
  highwire: {DOI: [...]},
  twitter: {SITE: [...]}
}
```

Now, with the modifications introduced in this PR, it produces a
metadata dictionary where all the keys are lowercase:
```
{
  dc: {identifier: [...] },
  eprints: {title: [...]},
  facebook: {url: [...]},
  highwire: {doi: [...]},
  twitter: {site: [...]}
}
```

I have confirmed that `h` expects the lowercase version of the keys
`identifier` and `doi`:

https://github.com/hypothesis/h/blob/73dacc722367c44903ff3c6f610712ba8f43934d/h/util/document_claims.py#L222

https://github.com/hypothesis/h/blob/73dacc722367c44903ff3c6f610712ba8f43934d/h/util/document_claims.py#L247

Hence, if they are not provided as lowercase version, they will be
ignored and the document equivalence will not work.

Closes #671
Closes https://github.com/hypothesis/h/issues/6705

2022-02-11 08:11 UTC, robertknight commented
> Closes https://github.com/hypothesis/h/issues/6705

I don't think should close the h issue with this PR, since the problem will still exist for anyone submitting annotations manually to the h API. If h is supposed to handle these values in a case-insensitive way, that needs to be done on the h side. Having the client case-fold the property values is I think worth doing as well, since it will avoid problems if client-side code tries to read them.

2022-02-11 08:25 UTC, robertknight requested changes
I think it does make sense to make this change on the client side, although if h has conditional logic that involves property names it should really handle the case-insensitivity on its side too.

For this PR I noted that the lower-casing should be done in a way that is consistent between different users' systems.

2022-02-11 12:28 UTC, esanzgar commented on src/annotator/integrations/html-metadata.js
> +          const key = match[1].toLocaleLowerCase();
Sorry, my mistake... (it was originally `toLowerCase` but in another position and when I moved here I made the mistake).

Thanks for catching it up.

2022-02-11 12:42 UTC, esanzgar commented on src/annotator/integrations/test/html-metadata-test.js
> +      it('should ignore casing of the text in the "name" attribute', () => {
I changed the test description and changed a line to include with `property` as attribute name.

2022-02-11 12:48 UTC, esanzgar commented
I have removed the link to #6705. However, I personally think this is a client issue, not a backend issue.

2022-02-14 08:30 UTC, robertknight commented
This change would impact the data stored in the `document_meta.type` column in the h database going forwards, which other folks will need to be aware of.

[document-meta-query-result.csv](https://github.com/hypothesis/client/files/8059051/document-meta-query-result.csv) is a summary of the most frequent type values in the production `document_meta` table based on a 5% uniform sample. I used a sample because the table was too large to run the query otherwise in Metabase.

Note that the `type` values are not the exact contents of the `name` or `property` attributes in the `<meta>` tags in all cases. Rather they are based on the object that `DocumentMetadata` generates (for example `<meta name="citation_*">` tags result in `highwire`-prefixed entries in this table).

The query used in Metabase was:

```sql
select type, count(*) as count from document_meta tablesample system (5) group by type order by count desc;
```

From this data, the values for rows containing at least one upper case letter:

```
dc.Title,2445
dc.Identifier,2387
dc.Language,2312
dc.Publisher,2275
dc.Date,2142
dc.Type,1857
dc.Contributor,1562
dc.Format,1251
dc.Description,1134
dc.Rights,943
prism.publicationName,886
prism.publicationDate,868
prism.startingPage,801
dc.Creator,677
dc.ERMS.available,646
prism.endingPage,637
dc.ERMS.dateAccepted,625
dc.ERMS.extent,622
dc.ERMS.abstract,617
prism.rightsAgent,598
dc.ERMS.spatial,584
dc.rightsAgent,554
dc.ERMS.alternative,552
dc.Coverage,551
dc.Source,533
dc.Subject,516
dc.AccessRights,394
dc.ERMS.issued,312
dc.ext.pn_grID,162
dc.ext.pn_nID,153
dc.ext.doc_Abstract_available,148
dc.ext.ID_editeur,144
dc.ext.doc_PlanOfArticle_available,143
dc.ext.doc_SeeAlso_available,141
facebook.URL,125
dc.erms.Date,121
facebook.Type,118
facebook.Image,118
dc.erms.Coverage,117
dc.erms.Relation,117
dc.erms.Title,116
dc.erms.Contributor,116
dc.erms.Rights,114
dc.Relation,114
dc.erms.Language,112
dc.erms.Publisher,110
facebook.Title,110
dc.erms.Identifier,107
dc.erms.Type,106
dc.erms.Description,105
dc.erms.Format,100
prism.issueName,99
dc.ext.inst_ID,94
dc.Date.modified,93
dc.ERMS.modified,84
dc.Identifier.URI,80
dc.Source.URI,79
dc.Date.issued,78
dc.relation.isPartOf,75
dc.Date.Created,74
dc.Date.created,74
dc.Date.Modified,74
dc.erms.Creator,73
dc.Source.ISSN,72
dc.Date.dateSubmitted,71
prism.eIssn,70
dc.Source.Volume,68
dc.erms.rightsHolder,67
dc.Type.articleType,66
dc.erms.dateCopyrighted,66
dc.Source.Issue,66
dc.ext.DartZone,65
dc.ext.ChannelList,64
dc.Created,61
dc.Publishers,59
dc.erms.Subject,59
dc.Creator.PersonalName,59
dc.title.Main,50
prism.corporateEntity,44
dc.Contributor.Sponsor,43
dc.ext.ContentChannel,43
dc.Identifier.pageNumber,41
dc.erms.isPartOf,37
dc.Identifier.DOI,37
prism.aggregationType,36
dc.ERMS.created,29
dc.ERMS.title,24
dc.ext.Category,24
dc.erms:isPartOf,22
dc.description.tableOfContents,22
dc.ERMS.bibliographicCitation,22
dc.erms:hasFormat,22
dc.ext.articleId,21
twitter.imageUrl,21
facebook.Description,20
dc.ext.Channel,20
dc.ERMS.language,20
dc.ERMS.subject,18
dc.ext.campaignId,18
dc.ext.Content_Type,18
dc.erms.isVersionOf,18
dc.title.Subtitle,18
dc.ext.MLC,17
dc.ERMS.creator,17
dc.ERMS.description,17
dc.Date.Issued,17
dc.Description.Abstract,16
dc.ext.Level,16
dc.ERMS.identifier,15
dc.ERMS.publisher,15
dc.Coverage.spatial,15
dc.Title.Alternative,15
dc.ext.campaignStart,15
dc.ext.Genre,14
dc.ext.campaignEnd,14
facebook.regDate,14
dc.ext.FullHTMLview,14
dc.ext.articleFirstPublished,14
dc.isPartOf,12
dc.ERMS.isPartOf,11
dc.ERMS.rights,11
dc.Relation.IsPartOf,10
dc.Issued,10
dc.Coverage.temporal,9
dc.ERMS.type,9
dc.ERMS.source,8
dc.Date.X-MetadataLastModified,8
dc.ext.appUIVersion,7
dc.ext.cmsSect,7
dc.ext.sessionId,7
dc.Publisher.Address,7
dc.ERMS.ispartof,7
dc.ext.WebsiteName,7
dc.ERMS.format,7
dc.ext.AbsHTMLview,6
dc.Contributor.PersonalName,6
dc.Subject.epachannel,5
facebook.EmailBody,5
dc.ext.WT_doi,5
dc.Identifier.URL,5
dc.ext.ContentType,5
dc.ext.WT_volume,5
dc.Relation.Replaces,5
facebook.pixelID,5
dc.ext.ContentHeadline,5
facebook.EmailSubject,5
dc.ext.WT_name,5
prism.coverDisplayDate,4
dc.relation:isPartOf,4
facebook.Locale,4
dc.ext.rChannel,4
dc.rightsHolder,4
dc.creator.CorporateName,4
dc.erms.accessRights,4
dc.Keywords,4
dc.ext.PageTotal,4
dc.ERMS.rightsHolder,4
dc.PageID,4
dc.identifier.DOI,4
dc.ERMS.temporal,4
dc.Publisher.CorporateName,4
dc.ERMS.date,4
dc.ext.rAuthor,4
dc.dateSubmitted,4
prism.issnOnline,3
dc.LANGUAGE,3
dc.Creator.CoporateName,3
dc.Rights.Copyright,3
dc.ext.WT_issue,3
dc.ext.WT_Subject,3
dc.erms:dateModified,3
dc.ext.WT_issn,3
facebook.modDate,3
dc.Creator.PersonalName.Address,3
dc.ERMS:interactiveResource,3
dc.Rights.RightsHolder,3
dc.ERMS.license,3
prism.issnPrint,3
dc.dateAccepted,3
dc.Format.MIME,3
dc.Type.category,3
dc.Creator.Address,3
prism.issueIdentifier,3
dc..appliesToProduct,3
dc.identifier.URL,2
highwire.eJpId,2
dc.ERMS.contributor,2
dc..appliesToTechnology,2
dc.ERMS.relation,2
dc.Coverage.t.min,2
dc.Identifier.Slug,2
dc.ext.PageNumber,2
dc.Audience,2
dc.Coverage.Placename.Area,2
dc.ERMS:contentOwner,2
dc.Audience.Mediator,2
dc.Date.valid,2
dc.ERMS.FileFormat,2
dc.Coverage.PlaceName,2
dc.ERMS.Created,2
dc..appliesToVersion,2
dc.Date.available,2
dc.Subject.eparit,2
dc.ERMS.Issued,2
facebook.Url,2
twitter.Image,2
dc.Description.TableofContents,2
dc.ERMS.tableOfContents,2
dc.publisher.CorporateName,2
dc.ERMS.Description,2
dc.Language.Preference,2
dc.Coverage.t.max,2
dc.Format.Binding,2
dc.Format.SysReq,2
facebook.pubDate,2
dc.relation.isPartOf.Human,2
dc.ERMS.Modified,2
dc.Type.Status,2
dc.Subject.Keyword,2
prism.academicField,2
dc.Identifier.RAND,2
dc.ERMS.coverage,2
prism.publication.Name,2
dc.ext.rCountry,2
dc.Modified,2
dc.DateCreated,1
dc.Date.Modification,1
dc.ERMS.valid,1
facebook.smanArticleUrl,1
dc.ERMS.date.created,1
prism.stationCallSign,1
dc.Creator.CorporateName,1
dc.ERMS.updated,1
dc.ext.Dimension_FUZE_Category_Level_1,1
dc.ext.Dimension_FUZE_SNAPS_Placement,1
dc.accessRights,1
dc.ERMS.hasFormat,1
dc.ext.Server,1
dc.Availability,1
dc.lmuSiteName,1
dc.Date.modification,1
dc.Format.Media,1
dc.ext.Dimension_FUZE_Category_Level_2,1
dc.ext.gpimSourced,1
dc.ERMS.audience,1
dc.Rights.Owner,1
facebook.smanMobileUrl,1
dc.ext.BM_Section1,1
dc.ERMS.date.modified,1
dc.Date.published,1
dc.Date.publicationOriginal,1
dc.Date.ValidFromF,1
dc.erms:hasPart,1
dc.relation.IsPartOf,1
highwire.ISSN,1
dc.DateModified,1
dc.Type.documentType,1
dc.DOI,1
dc.Date.Comment.End,1
dc.ERMS.dateSubmitted,1
dc.erms:dateCreated,1
dc.ext.MSDNLibraryNode,1
dc.Coverage.jurisdiction,1
dc.ext.qse_edu_quidget1_positionOrdering,1
dc.Date.publicationElectronic,1
dc.ext.BM_Section3,1
dc.Creator.PersonalName.Address.Email,1
dc.Rating,1
dc.Author,1
dc.ext.qse_edu_quidget1_enableComponents,1
dc.Subject.epahealth,1
dc.ERMS:coderOffice,1
dc.erms.bibliographicCitation,1
dc.rights.intellectualProperty,1
dc.Copyright,1
dc.Publisher.Corporate,1
dc.ext.LastUpdateDate,1
dc.ext.Dimension_FUZE_Market_Level_2,1
dc.erms:accessRights,1
prism.stationId,1
dc.Date.ValidToTmp,1
dc.Date.Comment.Start,1
dc.erms:rightsHolder,1
dc.ERMS:coder,1
facebook.smanCatID,1
dc.ERMS.Alternative,1
dc.Relation.isVersionOf,1
dc.Date.Valid,1
dc.dir.ClearVars,1
dc.ext.Dimension_FUZE_Market_Level_1,1
dc.ext.Hierarchy,1
dc.erms.dateAccepted,1
dc.ext.RealUrl,1
dc.Format.Pages,1
dc.ext.Dimension_zz_language,1
highwire.PDF_url,1
dc.Subject.epaindustry,1
dc.ext.BM_Section2,1
dc.RightsHolder,1
highwire.issnPrint,1
twitter.URL,1
dc.ERMS.isFormatOf,1
dc.ERMS:dateCertified,1
dc.ERMS_description,1
prism.versionIdentifier,1
dc.ext.BRCountry,1
dc.Subject.MeSH,1
twitter.hashTags,1
dc.timeCreated,1
dc.Subject.epaect,1
dc.Date.availableated,1
dc.Creator.Personal,1
dc.Unused,1
dc.Publisher.Personal,1
facebook.IsPay,1
dc.Title.Alternate,1
dc.Function,1
dc.DESCRIPTION,1
dc.Subject.Keywords,1
dc.Source.Description,1
dc.Subject.epasubstance,1
dc.Date.Available,1
dc.ext.Dimension_FUZE_Product_Family_Level_2,1
dc.ERMS_identifier,1
dc.ext.PartStatus,1
dc.erms.IsPartOf,1
```

2022-02-14 08:53 UTC, robertknight commented
Summary of the most popular metadata property names from the 5% sample of the production `document_meta` which have been observed with different casings:

```
documentfingerprint [('documentFingerprint', 61420), ('documentfingerprint', 39)]
facebook.title [('facebook.title', 49707), ('facebook.Title', 110)]
facebook.image [('facebook.image', 47254), ('facebook.Image', 118)]
facebook.description [('facebook.description', 46360), ('facebook.Description', 20)]
facebook.type [('facebook.type', 46012), ('facebook.Type', 118)]
facebook.url [('facebook.url', 45622), ('facebook.URL', 125), ('facebook.Url', 2)]
twitter.image [('twitter.image', 19191), ('twitter.Image', 2)]
facebook.locale [('facebook.locale', 14851), ('facebook.Locale', 4)]
dc.identifier [('dc.identifier', 5904), ('dc.Identifier', 2387)]
twitter.url [('twitter.url', 6496), ('twitter.URL', 1)]
dc.title [('dc.title', 2960), ('dc.Title', 2445)]
dc.publisher [('dc.publisher', 2624), ('dc.Publisher', 2275)]
highwire.pdf_url [('highwire.pdf_url', 4785), ('highwire.PDF_url', 1)]
dc.date [('dc.date', 2510), ('dc.Date', 2142)]
highwire.issn [('highwire.issn', 4547), ('highwire.ISSN', 1)]
dc.language [('dc.Language', 2312), ('dc.language', 1998), ('dc.LANGUAGE', 3)]
dc.type [('dc.Type', 1857), ('dc.type', 1631)]
dc.format [('dc.format', 2089), ('dc.Format', 1251)]
dc.creator [('dc.creator', 2125), ('dc.Creator', 677)]
dc.description [('dc.description', 1627), ('dc.Description', 1134), ('dc.DESCRIPTION', 1)]
dc.contributor [('dc.Contributor', 1562), ('dc.contributor', 887)]
dc.rights [('dc.rights', 1392), ('dc.Rights', 943)]
dc.subject [('dc.subject', 1563), ('dc.Subject', 516)]
dc.source [('dc.source', 1443), ('dc.Source', 533)]
prism.publicationname [('prism.publicationName', 886), ('prism.publicationname', 3)]
prism.publicationdate [('prism.publicationDate', 868), ('prism.publicationdate', 5)]
prism.startingpage [('prism.startingPage', 801), ('prism.startingpage', 2)]
dc.relation [('dc.relation', 687), ('dc.Relation', 114)]
dc.erms.abstract [('dc.ERMS.abstract', 617), ('dc.erms.abstract', 61)]
dc.erms.available [('dc.ERMS.available', 646), ('dc.erms.available', 28)]
dc.erms.extent [('dc.ERMS.extent', 622), ('dc.erms.extent', 28)]
prism.endingpage [('prism.endingPage', 637), ('prism.endingpage', 1)]
dc.erms.dateaccepted [('dc.ERMS.dateAccepted', 625), ('dc.erms.dateaccepted', 1), ('dc.erms.dateAccepted', 1)]
dc.erms.spatial [('dc.ERMS.spatial', 584), ('dc.erms.spatial', 22)]
prism.rightsagent [('prism.rightsAgent', 598), ('prism.rightsagent', 1)]
dc.coverage [('dc.Coverage', 551), ('dc.coverage', 25)]
dc.copyright [('dc.copyright', 561), ('dc.Copyright', 1)]
dc.erms.alternative [('dc.ERMS.alternative', 552), ('dc.ERMS.Alternative', 1)]
dc.erms.title [('dc.erms.title', 404), ('dc.erms.Title', 116), ('dc.ERMS.title', 24)]
dc.erms.identifier [('dc.erms.identifier', 323), ('dc.erms.Identifier', 107), ('dc.ERMS.identifier', 15)]
dc.erms.issued [('dc.ERMS.issued', 312), ('dc.erms.issued', 93), ('dc.ERMS.Issued', 2)]
dc.erms.date [('dc.erms.date', 281), ('dc.erms.Date', 121), ('dc.ERMS.date', 4)]
dc.erms.description [('dc.erms.description', 277), ('dc.erms.Description', 105), ('dc.ERMS.description', 17), ('dc.ERMS.Description', 2)]
dc.erms.type [('dc.erms.type', 285), ('dc.erms.Type', 106), ('dc.ERMS.type', 9)]
dc.accessrights [('dc.AccessRights', 394), ('dc.accessRights', 1), ('dc.accessrights', 1)]
dc.erms.creator [('dc.erms.creator', 305), ('dc.erms.Creator', 73), ('dc.ERMS.creator', 17)]
dc.relation.ispartof [('dc.relation.ispartof', 291), ('dc.relation.isPartOf', 75), ('dc.Relation.IsPartOf', 10), ('dc.relation.IsPartOf', 1)]
dc.date.issued [('dc.date.issued', 244), ('dc.Date.issued', 78), ('dc.Date.Issued', 17)]
dc.erms.format [('dc.erms.format', 232), ('dc.erms.Format', 100), ('dc.ERMS.format', 7)]
dc.erms.language [('dc.erms.language', 168), ('dc.erms.Language', 112), ('dc.ERMS.language', 20)]
dc.erms.modified [('dc.erms.modified', 159), ('dc.ERMS.modified', 84), ('dc.ERMS.Modified', 2)]
dc.date.modified [('dc.Date.modified', 93), ('dc.date.modified', 77), ('dc.Date.Modified', 74)]
dc.erms.publisher [('dc.erms.Publisher', 110), ('dc.erms.publisher', 88), ('dc.ERMS.publisher', 15)]
dc.date.created [('dc.Date.Created', 74), ('dc.Date.created', 74), ('dc.date.created', 65)]
dc.erms.subject [('dc.erms.subject', 115), ('dc.erms.Subject', 59), ('dc.ERMS.subject', 18)]
facebook.pubdate [('facebook.pubdate', 162), ('facebook.pubDate', 2)]
dc.erms.rights [('dc.erms.Rights', 114), ('dc.erms.rights', 39), ('dc.ERMS.rights', 11)]
dc.ext.doc_planofarticle_available [('dc.ext.doc_PlanOfArticle_available', 143), ('dc.ext.doc_planofarticle_available', 1)]
dc.erms.created [('dc.erms.created', 102), ('dc.ERMS.created', 29), ('dc.ERMS.Created', 2)]
dc.erms.contributor [('dc.erms.Contributor', 116), ('dc.erms.contributor', 11), ('dc.ERMS.contributor', 2)]
dc.erms.coverage [('dc.erms.Coverage', 117), ('dc.erms.coverage', 7), ('dc.ERMS.coverage', 2)]
dc.erms.relation [('dc.erms.Relation', 117), ('dc.ERMS.relation', 2)]
prism.issuename [('prism.issueName', 99), ('prism.issuename', 1)]
dc.source.uri [('dc.Source.URI', 79), ('dc.source.uri', 9)]
dc.identifier.uri [('dc.Identifier.URI', 80), ('dc.identifier.uri', 6)]
dc.date.datesubmitted [('dc.Date.dateSubmitted', 71), ('dc.date.datesubmitted', 11)]
dc.source.issn [('dc.Source.ISSN', 72), ('dc.source.issn', 8)]
dc.source.volume [('dc.Source.Volume', 68), ('dc.source.volume', 8)]
dc.source.issue [('dc.Source.Issue', 66), ('dc.source.issue', 9)]
dc.type.articletype [('dc.Type.articleType', 66), ('dc.type.articletype', 8)]
dc.erms.rightsholder [('dc.erms.rightsHolder', 67), ('dc.ERMS.rightsHolder', 4), ('dc.erms.rightsholder', 2)]
prism.eissn [('prism.eIssn', 70), ('prism.eissn', 1)]
dc.erms.datecopyrighted [('dc.erms.dateCopyrighted', 66), ('dc.erms.datecopyrighted', 3)]
dc.creator.personalname [('dc.Creator.PersonalName', 59), ('dc.creator.personalname', 7)]
dc.ext.channellist [('dc.ext.ChannelList', 64), ('dc.ext.channellist', 1)]
dc.created [('dc.Created', 61), ('dc.created', 2)]
dc.publishers [('dc.Publishers', 59), ('dc.publishers', 2)]
dc.erms.ispartof [('dc.erms.isPartOf', 37), ('dc.ERMS.isPartOf', 11), ('dc.ERMS.ispartof', 7), ('dc.erms.IsPartOf', 1)]
dc.contributor.sponsor [('dc.Contributor.Sponsor', 43), ('dc.contributor.sponsor', 9)]
dc.issued [('dc.issued', 41), ('dc.Issued', 10)]
dc.ext.contentchannel [('dc.ext.ContentChannel', 43), ('dc.ext.contentchannel', 1)]
dc.erms.audience [('dc.erms.audience', 43), ('dc.ERMS.audience', 1)]
dc.identifier.pagenumber [('dc.Identifier.pageNumber', 41), ('dc.identifier.pagenumber', 3)]
dc.identifier.doi [('dc.Identifier.DOI', 37), ('dc.identifier.DOI', 4)]
prism.aggregationtype [('prism.aggregationType', 36), ('prism.aggregationtype', 4)]
dc.erms.source [('dc.erms.source', 28), ('dc.ERMS.source', 8)]
dc.keywords [('dc.keywords', 23), ('dc.Keywords', 4)]
dc.rights.owner [('dc.rights.owner', 25), ('dc.Rights.Owner', 1)]
dc.description.tableofcontents [('dc.description.tableOfContents', 22), ('dc.Description.TableofContents', 2)]
dc.erms.bibliographiccitation [('dc.ERMS.bibliographicCitation', 22), ('dc.erms.bibliographicCitation', 1)]
dc.ext.channel [('dc.ext.Channel', 20), ('dc.ext.channel', 2)]
dc.description.abstract [('dc.Description.Abstract', 16), ('dc.description.abstract', 6)]
dc.ext.campaignid [('dc.ext.campaignId', 18), ('dc.ext.campaignid', 1)]
dc.ext.content_type [('dc.ext.Content_Type', 18), ('dc.ext.content_type', 1)]
dc.ext.mlc [('dc.ext.MLC', 17), ('dc.ext.mlc', 1)]
dc.coverage.spatial [('dc.Coverage.spatial', 15), ('dc.coverage.spatial', 3)]
dc.title.alternative [('dc.Title.Alternative', 15), ('dc.title.alternative', 1)]
dc.ext.genre [('dc.ext.Genre', 14), ('dc.ext.genre', 1)]
dc.ext.campaignend [('dc.ext.campaignEnd', 14), ('dc.ext.campaignend', 1)]
dc.ext.articlefirstpublished [('dc.ext.articleFirstPublished', 14), ('dc.ext.articlefirstpublished', 1)]
dc.coverage.temporal [('dc.Coverage.temporal', 9), ('dc.cov [...]

2022-02-14 08:55 UTC, robertknight commented
> I have removed the link to https://github.com/hypothesis/h/issues/6705. However, I personally think this is a client issue, not a backend issue.

This is absolutely an issue for h, if it does anything with metadata property names beyond treating them as opaque strings. The client is the biggest user of the h API, but it is not the only one.

2022-02-16 12:10 UTC, robertknight approved these changes
LGTM. Based on the data analysis I did it is common that property names are seen with different casings "in the wild", and h always expects the lower-cased variant from what I could see. I would suggest to create an issue to at least consider performing the same normalization on the h side, for the benefit of other h API clients.

2022-02-16 12:45 UTC, merged